{PauliusKup/DomainFramework/Impl/globalConfigLine.i {&CONFIG1}}
{PauliusKup/DomainFramework/Impl/globalConfigLine.i {&CONFIG2}}
{PauliusKup/DomainFramework/Impl/globalConfigLine.i {&CONFIG3}}
{PauliusKup/DomainFramework/Impl/globalConfigLine.i {&CONFIG4}}
{PauliusKup/DomainFramework/Impl/globalConfigLine.i {&CONFIG5}}
{PauliusKup/DomainFramework/Impl/globalConfigLine.i {&CONFIG6}}
{PauliusKup/DomainFramework/Impl/globalConfigLine.i {&CONFIG7}}
{PauliusKup/DomainFramework/Impl/globalConfigLine.i {&CONFIG8}}
{PauliusKup/DomainFramework/Impl/globalConfigLine.i {&CONFIG9}}
{PauliusKup/DomainFramework/Impl/globalConfigLine.i {&CONFIG10}}
{PauliusKup/DomainFramework/Impl/globalConfigLine.i {&CONFIG11}}
{PauliusKup/DomainFramework/Impl/globalConfigLine.i {&CONFIG12}}
{PauliusKup/DomainFramework/Impl/globalConfigLine.i {&CONFIG13}}
{PauliusKup/DomainFramework/Impl/globalConfigLine.i {&CONFIG14}}
{PauliusKup/DomainFramework/Impl/globalConfigLine.i {&CONFIG15}}
{PauliusKup/DomainFramework/Impl/globalConfigLine.i {&CONFIG16}}
{PauliusKup/DomainFramework/Impl/globalConfigLine.i {&CONFIG17}}
{PauliusKup/DomainFramework/Impl/globalConfigLine.i {&CONFIG18}}
{PauliusKup/DomainFramework/Impl/globalConfigLine.i {&CONFIG19}}
{PauliusKup/DomainFramework/Impl/globalConfigLine.i {&CONFIG20}}
{PauliusKup/DomainFramework/Impl/globalConfigLine.i {&CONFIG21}}
{PauliusKup/DomainFramework/Impl/globalConfigLine.i {&CONFIG22}}
{PauliusKup/DomainFramework/Impl/globalConfigLine.i {&CONFIG23}}
{PauliusKup/DomainFramework/Impl/globalConfigLine.i {&CONFIG24}}
{PauliusKup/DomainFramework/Impl/globalConfigLine.i {&CONFIG25}}
{PauliusKup/DomainFramework/Impl/globalConfigLine.i {&CONFIG26}}
{PauliusKup/DomainFramework/Impl/globalConfigLine.i {&CONFIG27}}
{PauliusKup/DomainFramework/Impl/globalConfigLine.i {&CONFIG28}}
{PauliusKup/DomainFramework/Impl/globalConfigLine.i {&CONFIG29}}
{PauliusKup/DomainFramework/Impl/globalConfigLine.i {&CONFIG30}}